### ISSUE TITLE
when user clicks enter on one of the suggestions the on select is fired but the text is not entered in the summernote

### ISSUE THREAD

**Issue by vasudevravula** [team-loxo/summernote-at-mention#1]

**Comment by seangarita** [comment]
Are you passing an `onSelect` callback? If so, this is intended behavior since we assume you want to do your own thing and not necessarily insert the text. That being said, if you would like to do both, maybe we can pass in an option `alwaysInsertsText` which, if true, always inserts the text, even if an `onSelect` callback is passed.
